# -*- coding: utf-8 -*-
"""spleeter_for_video_splitting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VkyHt0Eaw7Atloj5WF3wMxpoRVT2fpIv
"""

from IPython.display import Audio

"""# Separate from command line

#Video 1
"""

Audio("Video_1.mp3")

!spleeter separate -o output/ Video_1.mp3

Audio('output/Video_1/vocals.wav')

"""#Video 2"""

!spleeter separate -o output/ Video_2.mp3

Audio("output/Video_2/vocals.wav")

"""#Video 3"""

!spleeter separate -o output/ Video_3.mp3

Audio("output/Video_3/vocals.wav")